services:
  web:
    container_name: domain_whois
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 --workers=2 project.__init__:app
    ports:
      - 8094:5000
    volumes:
      - ./services/web:/usr/src/app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=production